# Generated by Django 4.2.7 on 2023-11-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_oderdetails_shoppingsession_oderitem_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingSession',
            new_name='Cart',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='session',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
        migrations.DeleteModel(
            name='OderDetails',
        ),
        migrations.DeleteModel(
            name='OderItem',
        ),
    ]
